Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3455,6 +3455,12 @@ _ACEOF
 
   LIBS="-lz $LIBS"
 
+else
+
+{ { echo "$as_me:$LINENO: error: the zlib library is required" >&5
+echo "$as_me: error: the zlib library is required" >&2;}
+   { (exit 1); exit 1; }; }
+
 fi
 
 
@@ -4418,7 +4424,8 @@ done
 
 
 
-for ac_header in unistd.h getopt.h utime.h stdarg.h varargs.h
+
+for ac_header in unistd.h getopt.h utime.h stdarg.h varargs.h stdint.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
